// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/v1/authentication_verifier_api.proto

package dockerregistryproxyv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// VerifyRequest represents a message for an AuthenticationVerifier to verify.
type VerifyRequest struct {
	// username represents the username portion of the basic auth received from
	// the docker client.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// password represents the password portion of the basic auth received from
	// the docker client.
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// host represents the host of the image that the docker client is attempting
	// to pull. e.g. docker-proxy.example.org
	Host string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	// repository represents the repository of the image that the docker client is
	// attempting to pull. e.g. my-repository
	Repository string `protobuf:"bytes,4,opt,name=repository,proto3" json:"repository,omitempty"`
	// image represents the image that the docker client is attempting to pull.
	// e.g. my-image:latest or my-image@sha256:digest
	Image                string   `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_834085af0e9ab970, []int{0}
}

func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(m, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *VerifyRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *VerifyRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *VerifyRequest) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *VerifyRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

// VerifyResponse is empty.
type VerifyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyResponse) Reset()         { *m = VerifyResponse{} }
func (m *VerifyResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyResponse) ProtoMessage()    {}
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_834085af0e9ab970, []int{1}
}

func (m *VerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyResponse.Unmarshal(m, b)
}
func (m *VerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyResponse.Marshal(b, m, deterministic)
}
func (m *VerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyResponse.Merge(m, src)
}
func (m *VerifyResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyResponse.Size(m)
}
func (m *VerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*VerifyRequest)(nil), "vjftw.dockerregistryproxy.v1.VerifyRequest")
	proto.RegisterType((*VerifyResponse)(nil), "vjftw.dockerregistryproxy.v1.VerifyResponse")
}

func init() {
	proto.RegisterFile("api/proto/v1/authentication_verifier_api.proto", fileDescriptor_834085af0e9ab970)
}

var fileDescriptor_834085af0e9ab970 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0x49, 0xf7, 0x07, 0x0d, 0x28, 0x12, 0x14, 0xea, 0x18, 0x63, 0xec, 0x4a, 0x50, 0x52,
	0xaa, 0x4f, 0xb0, 0xb1, 0x1b, 0xef, 0xca, 0x2e, 0x82, 0xc8, 0x60, 0xc4, 0xee, 0x6c, 0x8b, 0xd2,
	0x26, 0x26, 0x69, 0x67, 0xef, 0x7c, 0x05, 0x9f, 0x40, 0xf0, 0xd2, 0x47, 0xf1, 0xa9, 0xa4, 0xe9,
	0x26, 0x0e, 0xea, 0xf0, 0x2e, 0x27, 0xbf, 0xef, 0x3b, 0x7c, 0x1f, 0x07, 0x53, 0xae, 0x44, 0xa0,
	0xb4, 0xb4, 0x32, 0xc8, 0xc3, 0x80, 0x67, 0x76, 0x05, 0xa9, 0x15, 0x31, 0xb7, 0x42, 0xa6, 0xb3,
	0x1c, 0xb4, 0x58, 0x08, 0xd0, 0x33, 0xae, 0x04, 0x75, 0x22, 0xd2, 0xcd, 0x1f, 0x17, 0x76, 0x4d,
	0xe7, 0x32, 0x7e, 0x02, 0xad, 0x61, 0x29, 0x8c, 0xd5, 0x85, 0xd2, 0xf2, 0xa5, 0xa0, 0x79, 0x38,
	0x78, 0x43, 0xf8, 0x88, 0x95, 0xa6, 0x62, 0x02, 0xcf, 0x19, 0x18, 0x4b, 0x3a, 0xf8, 0x20, 0x33,
	0xa0, 0x53, 0x9e, 0x80, 0x8f, 0xfa, 0xe8, 0xe2, 0x70, 0xf2, 0x33, 0x97, 0x4c, 0x71, 0x63, 0xd6,
	0x52, 0xcf, 0x7d, 0xaf, 0x62, 0xdb, 0x99, 0x10, 0xdc, 0x5c, 0x49, 0x63, 0xfd, 0x86, 0xfb, 0x77,
	0x6f, 0xd2, 0xc3, 0x58, 0x83, 0x92, 0x46, 0x58, 0xa9, 0x0b, 0xbf, 0xe9, 0xc8, 0xaf, 0x1f, 0x72,
	0x8a, 0x5b, 0x22, 0xe1, 0x4b, 0xf0, 0x5b, 0x0e, 0x55, 0xc3, 0xe0, 0x04, 0x1f, 0x6f, 0x23, 0x19,
	0x25, 0x53, 0x03, 0xd7, 0xaf, 0x08, 0x9f, 0x0f, 0x77, 0x9a, 0xb2, 0x4d, 0xd1, 0x61, 0x74, 0x4b,
	0x62, 0xdc, 0xae, 0xf4, 0xe4, 0x92, 0xee, 0x2b, 0x4b, 0x77, 0x8a, 0x76, 0xae, 0xfe, 0x27, 0xae,
	0x22, 0x8c, 0xde, 0x11, 0xee, 0xc7, 0x32, 0xd9, 0xeb, 0x19, 0xf5, 0xfe, 0x08, 0xa9, 0x44, 0x54,
	0xde, 0x22, 0x42, 0xf7, 0x67, 0x35, 0xce, 0x3c, 0xfc, 0xf0, 0x1a, 0x6c, 0x7c, 0xf7, 0xe9, 0x75,
	0x99, 0xdb, 0x3e, 0xae, 0xd9, 0xce, 0xc2, 0xaf, 0x0d, 0x9e, 0xd6, 0xe0, 0x29, 0x0b, 0x1f, 0xda,
	0xee, 0xde, 0x37, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x34, 0x3c, 0x48, 0x60, 0x21, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthenticationVerifierAPIClient is the client API for AuthenticationVerifierAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationVerifierAPIClient interface {
	// Verify takes the raw Base64 encoded BasicAuth credential supplied to
	// the Docker Registry Proxy from the Docker client and authenticates
	// with the implementation.
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
}

type authenticationVerifierAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticationVerifierAPIClient(cc grpc.ClientConnInterface) AuthenticationVerifierAPIClient {
	return &authenticationVerifierAPIClient{cc}
}

func (c *authenticationVerifierAPIClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, "/vjftw.dockerregistryproxy.v1.AuthenticationVerifierAPI/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationVerifierAPIServer is the server API for AuthenticationVerifierAPI service.
type AuthenticationVerifierAPIServer interface {
	// Verify takes the raw Base64 encoded BasicAuth credential supplied to
	// the Docker Registry Proxy from the Docker client and authenticates
	// with the implementation.
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
}

// UnimplementedAuthenticationVerifierAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticationVerifierAPIServer struct {
}

func (*UnimplementedAuthenticationVerifierAPIServer) Verify(ctx context.Context, req *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}

func RegisterAuthenticationVerifierAPIServer(s *grpc.Server, srv AuthenticationVerifierAPIServer) {
	s.RegisterService(&_AuthenticationVerifierAPI_serviceDesc, srv)
}

func _AuthenticationVerifierAPI_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationVerifierAPIServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vjftw.dockerregistryproxy.v1.AuthenticationVerifierAPI/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationVerifierAPIServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthenticationVerifierAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vjftw.dockerregistryproxy.v1.AuthenticationVerifierAPI",
	HandlerType: (*AuthenticationVerifierAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Verify",
			Handler:    _AuthenticationVerifierAPI_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/authentication_verifier_api.proto",
}
