// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/v1/authentication.proto

package dockerregistryproxyv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// VerifyRequest represents a message for an AuthenticationVerifier to verify.
type VerifyRequest struct {
	// username represents the username portion of the basic auth received from
	// the docker client.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// password represents the password portion of the basic auth received from
	// the docker client.
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// host represents the host of the image that the docker client is attempting
	// to pull. e.g. docker-proxy.example.org
	Host string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	// repository represents the repository of the image that the docker client is
	// attempting to pull. e.g. my-repository
	Repository string `protobuf:"bytes,4,opt,name=repository,proto3" json:"repository,omitempty"`
	// image represents the image that the docker client is attempting to pull.
	// e.g. my-image:latest or my-image@sha256:digest
	Image                string   `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_df441e38b38b0fba, []int{0}
}

func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(m, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *VerifyRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *VerifyRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *VerifyRequest) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *VerifyRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

// ProvideRequest represents a message for an AuthenticationProvider to return
// credentials for.
type ProvideRequest struct {
	// host represents the host of the image that the docker client is attempting
	// to pull. e.g. docker-proxy.example.org
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// repository represents the repository of the image that the docker client is
	// attempting to pull. e.g. my-repository
	Repository string `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	// image represents the image that the docker client is attempting to pull.
	// e.g. my-image:latest or my-image@sha256:digest
	Image                string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvideRequest) Reset()         { *m = ProvideRequest{} }
func (m *ProvideRequest) String() string { return proto.CompactTextString(m) }
func (*ProvideRequest) ProtoMessage()    {}
func (*ProvideRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_df441e38b38b0fba, []int{1}
}

func (m *ProvideRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvideRequest.Unmarshal(m, b)
}
func (m *ProvideRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvideRequest.Marshal(b, m, deterministic)
}
func (m *ProvideRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvideRequest.Merge(m, src)
}
func (m *ProvideRequest) XXX_Size() int {
	return xxx_messageInfo_ProvideRequest.Size(m)
}
func (m *ProvideRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvideRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvideRequest proto.InternalMessageInfo

func (m *ProvideRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ProvideRequest) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *ProvideRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

// ProvideResponse represents the returned credentials.
type ProvideResponse struct {
	// Inlined what we use from github.com/cli/cli/config/types
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Auth     string `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	// IdentityToken is used to authenticate the user and get
	// an access token for the registry.
	IdentityToken string `protobuf:"bytes,4,opt,name=identity_token,json=identityToken,proto3" json:"identity_token,omitempty"`
	// RegistryToken is a bearer token to be sent to a registry
	RegistryToken        string   `protobuf:"bytes,5,opt,name=registry_token,json=registryToken,proto3" json:"registry_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvideResponse) Reset()         { *m = ProvideResponse{} }
func (m *ProvideResponse) String() string { return proto.CompactTextString(m) }
func (*ProvideResponse) ProtoMessage()    {}
func (*ProvideResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df441e38b38b0fba, []int{2}
}

func (m *ProvideResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvideResponse.Unmarshal(m, b)
}
func (m *ProvideResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvideResponse.Marshal(b, m, deterministic)
}
func (m *ProvideResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvideResponse.Merge(m, src)
}
func (m *ProvideResponse) XXX_Size() int {
	return xxx_messageInfo_ProvideResponse.Size(m)
}
func (m *ProvideResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvideResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProvideResponse proto.InternalMessageInfo

func (m *ProvideResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ProvideResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ProvideResponse) GetAuth() string {
	if m != nil {
		return m.Auth
	}
	return ""
}

func (m *ProvideResponse) GetIdentityToken() string {
	if m != nil {
		return m.IdentityToken
	}
	return ""
}

func (m *ProvideResponse) GetRegistryToken() string {
	if m != nil {
		return m.RegistryToken
	}
	return ""
}

func init() {
	proto.RegisterType((*VerifyRequest)(nil), "vjftw.dockerregistryproxy.v1.VerifyRequest")
	proto.RegisterType((*ProvideRequest)(nil), "vjftw.dockerregistryproxy.v1.ProvideRequest")
	proto.RegisterType((*ProvideResponse)(nil), "vjftw.dockerregistryproxy.v1.ProvideResponse")
}

func init() {
	proto.RegisterFile("api/proto/v1/authentication.proto", fileDescriptor_df441e38b38b0fba)
}

var fileDescriptor_df441e38b38b0fba = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x65, 0xd2, 0xdd, 0x55, 0x07, 0xba, 0xc2, 0xa8, 0x4b, 0x88, 0x8b, 0xac, 0x0b, 0x82, 0xa0,
	0x4e, 0xc8, 0xfa, 0x05, 0x2e, 0xeb, 0xa3, 0x50, 0x8a, 0x04, 0x29, 0x05, 0x49, 0x9b, 0x9b, 0x74,
	0xac, 0xc9, 0x8d, 0x33, 0x93, 0xd4, 0xbc, 0xf9, 0x0b, 0x82, 0x5f, 0xe0, 0xa3, 0xfe, 0x89, 0x5f,
	0x25, 0x99, 0xc9, 0x94, 0x56, 0xdb, 0x22, 0xf8, 0x36, 0xf7, 0x9c, 0x33, 0x67, 0xe6, 0xde, 0x73,
	0xe9, 0xe3, 0xa4, 0x12, 0x61, 0x25, 0x51, 0x63, 0xd8, 0x44, 0x61, 0x52, 0xeb, 0x05, 0x94, 0x5a,
	0xcc, 0x13, 0x2d, 0xb0, 0xe4, 0x06, 0x67, 0xe7, 0xcd, 0x87, 0x4c, 0xaf, 0x78, 0x8a, 0xf3, 0x25,
	0x48, 0x09, 0xb9, 0x50, 0x5a, 0xb6, 0x95, 0xc4, 0xcf, 0x2d, 0x6f, 0xa2, 0xe0, 0x61, 0x8e, 0x98,
	0x7f, 0x04, 0xeb, 0x31, 0xab, 0xb3, 0x10, 0x8a, 0x4a, 0xb7, 0xf6, 0xea, 0xe5, 0x57, 0x42, 0x87,
	0x31, 0x48, 0x91, 0xb5, 0x63, 0xf8, 0x54, 0x83, 0xd2, 0x2c, 0xa0, 0xb7, 0x6b, 0x05, 0xb2, 0x4c,
	0x0a, 0xf0, 0xc9, 0x05, 0x79, 0x7a, 0x67, 0xbc, 0xae, 0x3b, 0xae, 0x4a, 0x94, 0x5a, 0xa1, 0x4c,
	0x7d, 0xcf, 0x72, 0xae, 0x66, 0x8c, 0x1e, 0x2d, 0x50, 0x69, 0x7f, 0x60, 0x70, 0x73, 0x66, 0x8f,
	0x28, 0x95, 0x50, 0xa1, 0x12, 0x1a, 0x65, 0xeb, 0x1f, 0x19, 0x66, 0x03, 0x61, 0xf7, 0xe9, 0xb1,
	0x28, 0x92, 0x1c, 0xfc, 0x63, 0x43, 0xd9, 0xe2, 0x72, 0x42, 0x4f, 0x47, 0x12, 0x1b, 0x91, 0x82,
	0xfb, 0x93, 0xf3, 0x26, 0x7b, 0xbd, 0xbd, 0xfd, 0xde, 0x83, 0x4d, 0xef, 0x9f, 0x84, 0xde, 0x5d,
	0x9b, 0xab, 0x0a, 0x4b, 0x05, 0xff, 0xd3, 0x71, 0x17, 0x87, 0xeb, 0xb8, 0x3b, 0xb3, 0x27, 0xf4,
	0x54, 0xa4, 0x5d, 0x40, 0xba, 0x7d, 0xaf, 0x71, 0x09, 0x65, 0xdf, 0xf5, 0xd0, 0xa1, 0x6f, 0x3b,
	0xb0, 0x93, 0xb9, 0x9c, 0x7a, 0x99, 0x9d, 0xc0, 0xd0, 0xa1, 0x46, 0x76, 0x95, 0xd3, 0xb3, 0x57,
	0x5b, 0x81, 0x9b, 0xa8, 0x04, 0x48, 0xf6, 0x86, 0x9e, 0xd8, 0xd8, 0xd8, 0x33, 0x7e, 0x28, 0x7d,
	0xbe, 0x15, 0x6e, 0x70, 0xc6, 0xed, 0x32, 0x70, 0xb7, 0x0c, 0xfc, 0x75, 0xb7, 0x0c, 0x57, 0x5f,
	0xc8, 0x9f, 0x2f, 0xf5, 0x43, 0x92, 0x2c, 0xa3, 0xb7, 0xfa, 0x33, 0x7b, 0x7e, 0xf8, 0xa9, 0xed,
	0xd0, 0x82, 0x17, 0xff, 0xa8, 0xb6, 0x29, 0x5c, 0x7f, 0x23, 0xf4, 0x62, 0x8e, 0xc5, 0xc1, 0x4b,
	0xd7, 0xf7, 0xfe, 0xfa, 0xa4, 0xc6, 0x11, 0x99, 0x3c, 0xd8, 0x21, 0x6f, 0xa2, 0xef, 0xde, 0x20,
	0xbe, 0x79, 0xf7, 0xc3, 0x3b, 0x8f, 0x8d, 0xe5, 0xcd, 0x0e, 0xcb, 0x38, 0xfa, 0xd5, 0xd3, 0xd3,
	0x1d, 0xf4, 0x34, 0x8e, 0x66, 0x27, 0x66, 0x52, 0x2f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xb8,
	0xa5, 0xcb, 0x0e, 0x87, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthenticationVerifierClient is the client API for AuthenticationVerifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationVerifierClient interface {
	// Verify takes the raw Base64 encoded BasicAuth credential supplied to
	// the Docker Registry Proxy from the Docker client and authenticates
	// with the implementation.
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type authenticationVerifierClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticationVerifierClient(cc grpc.ClientConnInterface) AuthenticationVerifierClient {
	return &authenticationVerifierClient{cc}
}

func (c *authenticationVerifierClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/vjftw.dockerregistryproxy.v1.AuthenticationVerifier/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationVerifierServer is the server API for AuthenticationVerifier service.
type AuthenticationVerifierServer interface {
	// Verify takes the raw Base64 encoded BasicAuth credential supplied to
	// the Docker Registry Proxy from the Docker client and authenticates
	// with the implementation.
	Verify(context.Context, *VerifyRequest) (*empty.Empty, error)
}

// UnimplementedAuthenticationVerifierServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticationVerifierServer struct {
}

func (*UnimplementedAuthenticationVerifierServer) Verify(ctx context.Context, req *VerifyRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}

func RegisterAuthenticationVerifierServer(s *grpc.Server, srv AuthenticationVerifierServer) {
	s.RegisterService(&_AuthenticationVerifier_serviceDesc, srv)
}

func _AuthenticationVerifier_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationVerifierServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vjftw.dockerregistryproxy.v1.AuthenticationVerifier/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationVerifierServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthenticationVerifier_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vjftw.dockerregistryproxy.v1.AuthenticationVerifier",
	HandlerType: (*AuthenticationVerifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Verify",
			Handler:    _AuthenticationVerifier_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/authentication.proto",
}

// AuthenticationProviderClient is the client API for AuthenticationProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationProviderClient interface {
	Provide(ctx context.Context, in *ProvideRequest, opts ...grpc.CallOption) (*ProvideResponse, error)
}

type authenticationProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticationProviderClient(cc grpc.ClientConnInterface) AuthenticationProviderClient {
	return &authenticationProviderClient{cc}
}

func (c *authenticationProviderClient) Provide(ctx context.Context, in *ProvideRequest, opts ...grpc.CallOption) (*ProvideResponse, error) {
	out := new(ProvideResponse)
	err := c.cc.Invoke(ctx, "/vjftw.dockerregistryproxy.v1.AuthenticationProvider/Provide", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationProviderServer is the server API for AuthenticationProvider service.
type AuthenticationProviderServer interface {
	Provide(context.Context, *ProvideRequest) (*ProvideResponse, error)
}

// UnimplementedAuthenticationProviderServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticationProviderServer struct {
}

func (*UnimplementedAuthenticationProviderServer) Provide(ctx context.Context, req *ProvideRequest) (*ProvideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Provide not implemented")
}

func RegisterAuthenticationProviderServer(s *grpc.Server, srv AuthenticationProviderServer) {
	s.RegisterService(&_AuthenticationProvider_serviceDesc, srv)
}

func _AuthenticationProvider_Provide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationProviderServer).Provide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vjftw.dockerregistryproxy.v1.AuthenticationProvider/Provide",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationProviderServer).Provide(ctx, req.(*ProvideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthenticationProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vjftw.dockerregistryproxy.v1.AuthenticationProvider",
	HandlerType: (*AuthenticationProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Provide",
			Handler:    _AuthenticationProvider_Provide_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/authentication.proto",
}
