grpc_library(
    name = "v1",
    srcs = [
        "authentication_provider_api.proto",
        "authentication_verifier_api.proto",
        "configuration.proto",
        "configuration_api.proto",
    ],
    languages = ["go"],
    visibility = ["PUBLIC"],
)