// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/v1/configuration.proto

package dockerregistryproxyv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ConfigType represents the available field types from:
// https://github.com/spf13/viper#getting-values-from-viper
type ConfigType int32

const (
	ConfigType_CONFIG_TYPE_INVALID      ConfigType = 0
	ConfigType_CONFIG_TYPE_BOOL         ConfigType = 1
	ConfigType_CONFIG_TYPE_FLOAT64      ConfigType = 2
	ConfigType_CONFIG_TYPE_INT          ConfigType = 3
	ConfigType_CONFIG_TYPE_INT_SLICE    ConfigType = 4
	ConfigType_CONFIG_TYPE_STRING       ConfigType = 5
	ConfigType_CONFIG_TYPE_STRING_MAP   ConfigType = 6
	ConfigType_CONFIG_TYPE_STRING_SLICE ConfigType = 7
	ConfigType_CONFIG_TYPE_TIME         ConfigType = 8
	ConfigType_CONFIG_TYPE_DURATION     ConfigType = 9
)

var ConfigType_name = map[int32]string{
	0: "CONFIG_TYPE_INVALID",
	1: "CONFIG_TYPE_BOOL",
	2: "CONFIG_TYPE_FLOAT64",
	3: "CONFIG_TYPE_INT",
	4: "CONFIG_TYPE_INT_SLICE",
	5: "CONFIG_TYPE_STRING",
	6: "CONFIG_TYPE_STRING_MAP",
	7: "CONFIG_TYPE_STRING_SLICE",
	8: "CONFIG_TYPE_TIME",
	9: "CONFIG_TYPE_DURATION",
}

var ConfigType_value = map[string]int32{
	"CONFIG_TYPE_INVALID":      0,
	"CONFIG_TYPE_BOOL":         1,
	"CONFIG_TYPE_FLOAT64":      2,
	"CONFIG_TYPE_INT":          3,
	"CONFIG_TYPE_INT_SLICE":    4,
	"CONFIG_TYPE_STRING":       5,
	"CONFIG_TYPE_STRING_MAP":   6,
	"CONFIG_TYPE_STRING_SLICE": 7,
	"CONFIG_TYPE_TIME":         8,
	"CONFIG_TYPE_DURATION":     9,
}

func (x ConfigType) String() string {
	return proto.EnumName(ConfigType_name, int32(x))
}

func (ConfigType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_71e411e426306cd3, []int{0}
}

// ConfigurationAttribute represents a configuration attribute for a plugin.
type ConfigurationAttribute struct {
	AttributeType        ConfigType `protobuf:"varint,1,opt,name=attribute_type,json=attributeType,proto3,enum=vjftw.dockerregistryproxy.v1.ConfigType" json:"attribute_type,omitempty"`
	Description          string     `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ConfigurationAttribute) Reset()         { *m = ConfigurationAttribute{} }
func (m *ConfigurationAttribute) String() string { return proto.CompactTextString(m) }
func (*ConfigurationAttribute) ProtoMessage()    {}
func (*ConfigurationAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_71e411e426306cd3, []int{0}
}

func (m *ConfigurationAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigurationAttribute.Unmarshal(m, b)
}
func (m *ConfigurationAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigurationAttribute.Marshal(b, m, deterministic)
}
func (m *ConfigurationAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigurationAttribute.Merge(m, src)
}
func (m *ConfigurationAttribute) XXX_Size() int {
	return xxx_messageInfo_ConfigurationAttribute.Size(m)
}
func (m *ConfigurationAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigurationAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigurationAttribute proto.InternalMessageInfo

func (m *ConfigurationAttribute) GetAttributeType() ConfigType {
	if m != nil {
		return m.AttributeType
	}
	return ConfigType_CONFIG_TYPE_INVALID
}

func (m *ConfigurationAttribute) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// ConfigurationAttributeValue represents the value of a configuration attribute for a plugin.
type ConfigurationAttributeValue struct {
	AttributeType        ConfigType `protobuf:"varint,1,opt,name=attribute_type,json=attributeType,proto3,enum=vjftw.dockerregistryproxy.v1.ConfigType" json:"attribute_type,omitempty"`
	Value                []byte     `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ConfigurationAttributeValue) Reset()         { *m = ConfigurationAttributeValue{} }
func (m *ConfigurationAttributeValue) String() string { return proto.CompactTextString(m) }
func (*ConfigurationAttributeValue) ProtoMessage()    {}
func (*ConfigurationAttributeValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_71e411e426306cd3, []int{1}
}

func (m *ConfigurationAttributeValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigurationAttributeValue.Unmarshal(m, b)
}
func (m *ConfigurationAttributeValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigurationAttributeValue.Marshal(b, m, deterministic)
}
func (m *ConfigurationAttributeValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigurationAttributeValue.Merge(m, src)
}
func (m *ConfigurationAttributeValue) XXX_Size() int {
	return xxx_messageInfo_ConfigurationAttributeValue.Size(m)
}
func (m *ConfigurationAttributeValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigurationAttributeValue.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigurationAttributeValue proto.InternalMessageInfo

func (m *ConfigurationAttributeValue) GetAttributeType() ConfigType {
	if m != nil {
		return m.AttributeType
	}
	return ConfigType_CONFIG_TYPE_INVALID
}

func (m *ConfigurationAttributeValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterEnum("vjftw.dockerregistryproxy.v1.ConfigType", ConfigType_name, ConfigType_value)
	proto.RegisterType((*ConfigurationAttribute)(nil), "vjftw.dockerregistryproxy.v1.ConfigurationAttribute")
	proto.RegisterType((*ConfigurationAttributeValue)(nil), "vjftw.dockerregistryproxy.v1.ConfigurationAttributeValue")
}

func init() {
	proto.RegisterFile("api/proto/v1/configuration.proto", fileDescriptor_71e411e426306cd3)
}

var fileDescriptor_71e411e426306cd3 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xcd, 0xae, 0x93, 0x50,
	0x14, 0x85, 0x3d, 0xd4, 0x56, 0xbb, 0xd5, 0x7a, 0x72, 0xfa, 0x23, 0x6a, 0x07, 0xa4, 0xa3, 0xc6,
	0x01, 0x0d, 0x6a, 0x9c, 0xd3, 0xd2, 0x36, 0x24, 0x14, 0x08, 0x45, 0xa2, 0xa6, 0x09, 0xa1, 0x94,
	0x36, 0xf8, 0x53, 0xc8, 0xe9, 0x29, 0xca, 0xdc, 0x38, 0x71, 0xe8, 0x1b, 0x38, 0xf4, 0x51, 0x7c,
	0xaa, 0x1b, 0xe8, 0xfd, 0xa1, 0xbd, 0xa4, 0xb3, 0x3b, 0xdc, 0x6b, 0xed, 0xf5, 0xb1, 0xc2, 0xd9,
	0x20, 0x78, 0x71, 0x38, 0x88, 0x69, 0xc4, 0xa2, 0x41, 0x22, 0x0d, 0xfc, 0x68, 0xbb, 0x0e, 0x37,
	0x7b, 0xea, 0xb1, 0x30, 0xda, 0x8a, 0xb9, 0x4c, 0xba, 0xc9, 0xe7, 0x35, 0xfb, 0x2e, 0xae, 0x22,
	0xff, 0x4b, 0x40, 0x69, 0xb0, 0x09, 0x77, 0x8c, 0xa6, 0x31, 0x8d, 0x7e, 0xa4, 0x62, 0x22, 0xf5,
	0x7e, 0x23, 0xe8, 0x8c, 0x8a, 0x29, 0x99, 0x31, 0x1a, 0x2e, 0xf7, 0x2c, 0x20, 0x06, 0x34, 0xbc,
	0xab, 0xc1, 0x65, 0x69, 0x1c, 0xf0, 0x48, 0x40, 0xfd, 0xc6, 0xeb, 0xbe, 0x78, 0x8e, 0x28, 0x1e,
	0x68, 0x76, 0x1a, 0x07, 0xd6, 0x93, 0xeb, 0x7c, 0x36, 0x12, 0x01, 0x1e, 0xad, 0x82, 0x9d, 0x4f,
	0xc3, 0x38, 0xfb, 0x10, 0xcf, 0x09, 0xa8, 0x5f, 0xb7, 0x8a, 0x52, 0xef, 0x27, 0x82, 0x97, 0xe5,
	0x6d, 0x1c, 0xef, 0xeb, 0xfe, 0x0e, 0x2a, 0xb5, 0xa0, 0x9a, 0x64, 0xe4, 0xbc, 0xcc, 0x63, 0xeb,
	0x30, 0xbc, 0xfa, 0xc5, 0x01, 0xdc, 0x64, 0xc8, 0x33, 0x68, 0x8e, 0x0c, 0x7d, 0xa2, 0x4e, 0x5d,
	0xfb, 0xa3, 0x39, 0x76, 0x55, 0xdd, 0x91, 0x35, 0x55, 0xc1, 0xf7, 0x48, 0x0b, 0x70, 0xd1, 0x18,
	0x1a, 0x86, 0x86, 0xd1, 0xe9, 0xfa, 0x44, 0x33, 0x64, 0xfb, 0xdd, 0x5b, 0xcc, 0x91, 0x26, 0x3c,
	0x3d, 0xe6, 0xd8, 0xb8, 0x42, 0x9e, 0x43, 0xfb, 0x44, 0x74, 0xe7, 0x9a, 0x3a, 0x1a, 0xe3, 0xfb,
	0xa4, 0x03, 0xa4, 0x68, 0xcd, 0x6d, 0x4b, 0xd5, 0xa7, 0xb8, 0x4a, 0x5e, 0x40, 0xe7, 0xb6, 0xee,
	0xce, 0x64, 0x13, 0xd7, 0x48, 0x17, 0xf8, 0x12, 0xef, 0x40, 0x7c, 0x70, 0x5a, 0xd8, 0x56, 0x67,
	0x63, 0xfc, 0x90, 0xf0, 0xd0, 0x2a, 0xaa, 0xca, 0x7b, 0x4b, 0xb6, 0x55, 0x43, 0xc7, 0xf5, 0xe1,
	0x1f, 0x04, 0x82, 0x1f, 0x7d, 0x3b, 0xfb, 0x77, 0x87, 0xe4, 0xe8, 0xc5, 0xcc, 0xec, 0xe8, 0x4c,
	0xf4, 0xa9, 0x5d, 0xb2, 0x9d, 0x48, 0x7f, 0xb9, 0x8a, 0xa3, 0x7c, 0xf8, 0xc7, 0x75, 0x9d, 0x9c,
	0xa8, 0x94, 0x10, 0x1d, 0xe9, 0xff, 0xa5, 0xbd, 0x28, 0xb1, 0x17, 0x8e, 0xb4, 0xac, 0xe5, 0x87,
	0xfd, 0xe6, 0x22, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x36, 0xdc, 0x9a, 0xfc, 0x02, 0x00, 0x00,
}
