go_library(
    name = "cmd",
    srcs = [
        "cmd.go",
        "grpc.go",
        "http.go",
        "log.go",
        "plugin.go",
    ],
    deps = [
        "//pkg/plugin",
        "//third_party/go:grpc",
    ],
    visibility = ["PUBLIC"],
)