---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-proxy
  labels:
    app: docker-registry-proxy
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8888
  selector:
    app: docker-registry-proxy
