go_binary(
    name = "gcp-instanceidentitydocument",
    srcs = ["main.go"],
    deps = [
        "//api/proto/v1",
        "//pkg/auth/gcp",
        "//pkg/plugin",
        "//third_party/go:protobuf",
    ],
)
