go_library(
    name = "aws",
    srcs = [
        "certificates.go",
        "instanceidentitydocument-provider.go",
        "instanceidentitydocument-verifier.go",
        "metadata.go",
    ],
    visibility = [
        "//cmd/credential-providers/...",
        "//cmd/credential-verifiers/...",
    ],
)
