---
bases:
  - ../../../docker-registry-proxy/k8s/base
namespace: docker-registry-proxy

resources:
  - ingress.yaml

patches:
  - gcr.yaml

secretGenerator:
  - name: gcp-sa
    files:
      - gcp-sa.json
