name: Publish
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Please build
        run: ./pleasew build //...

      - name: Create pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./pleasew run //scripts:pre-release

      - name: Publish Docker images
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./pleasew run //scripts:publish-docker
