name: Test
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Please build
        run: ./pleasew build //...

      - name: Please lint
        run: ./pleasew lint
      
      - name: Please test
        run: ./pleasew test
