name: Test
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Please build
        run: ./pleasew build

      - name: Please lint
        run: ./pleasew lint
      
      - name: Please test
        run: ./pleasew test
